import type { Metadata } from "next";
import localFont from 'next/font/local';
import styles from '../styles/globals.css';
import {Navigation} from '../components/navigation';
import Footer from '../components/footer';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Mi App Web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title> App web </title>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav> 
          <h1>Menu</h1> 
        </nav>
        <Navigation />
        subWiki
        {children}

      <Footer />

      </body>
    </html>
  );
}
